### ISSUE TITLE
数式のmarkdown viewでのパースのfix(機能追加、簡単）

### ISSUE THREAD

**Issue by karino2** [karino2/kotlin-lesson#10]
### 概要

数式のmarkdown view、ドルドルで始まってドルドルで終わる行があると、間で閉じられてもmath modeと勘違いしている

https://github.com/karino2/kotlitex/issues/123

### やる事

たぶん正規表現を変更して、間にドルドルが無い、という条件にする、くらい。
ドルが一つある場合などはあまり発生しないので割と手抜きでもいいです。

正規表現練習とPR練習用に。

### 難易度

簡単。肩慣らしにどうぞ。

**Comment by karino2** [comment]
texには数式モードとテキストモードというのがある。
普通はテキストの中にインラインでドルで書かれたらテキストモード、独立した行にバックスラッシュ大かっこで書かれたら数式モードになる。

**texのテキストモード**

```
aaa $ \sum _n k $ bbb
```

**texのdisplay mode**

```
\[
 \sum _n k
\]
```

MathJaxなどではこれをエミュレートする為、ドルドルだけの行があったら数式モード、テキストの中にドルドルがあったらインラインモードとして扱っている。

*** mathjaxのtext mode ***

同じ行の中に数式以外がある。

```
aaa $$ \sum _n k $$ bbb
```

*** mathjaxのdisplay mode ***

ドルドルの行は数式だけ。

```
aaa

$$ \sum _n k $$

bbb
```

kotlitexのMarkdown Viewではこの判定として、ドルドルで始まってドルドルで終わっていたらmath modeにしているが、この場合、以下みたいな時におかしな事が起こる。

```
$$ \sum_n k $$ hoehoge $$ a_n $$
```

ドルドルで始まって、中にドルドルがあって違うテキストがあり、また別の数式が始まって行が終わる、みたいなケース。
これを直したい。

**Comment by harukawa** [comment]
```
    @Test
    fun testOneNormal_mathStart_mathEnd() {
        target.oneLine("\$\$x^2\$\$abc\$\$y_2\$\$")

        assertEquals(1, handler.normals.size)
        assertEquals(2, handler.mathExps.size)

        handler.normals[0].assert(3, "abc")

        handler.mathExps[0].assert(0, "x^2")
        handler.mathExps[1].assert(2, "y_2")

    }
```
というテストをMathSpanBuilderTest.ktに作成してみました。

**Comment by karino2** [comment]
良さそうです。それで実装してください。

**Comment by harukawa** [comment]
了解です。

**Comment by karino2** [comment]
正規表現のテストもたせたら足しておいてください。

**Comment by harukawa** [comment]
MarkdownView.ktの修正をしてMathSpanBuilderTest.ktのテストが通りました。
正規表現のテストは「$$x^2$$$$y_2$$」というもので大丈夫でしょうか？

**Comment by karino2** [comment]
先にPRを見せもらえますか？

**Comment by harukawa** [comment]
すみません、今PR上げました。
