### ISSUE TITLE
gitter用、複数行入力マッシュルーム(単独アプリ、簡単）

### ISSUE THREAD

**Issue by karino2** [karino2/kotlin-lesson#13]
### 概要

gitterアプリが改行をサポートしていないので、複数行入力できるEditTextを張り付けただけのマッシュルームを作る。
gitterアプリがそのうち対応すると思うのでその時までのつなぎくらいの簡単な物で。

### 必要な事

- intentを受け取り、結果を返す（マッシュルームの仕様は教えます）
- EditTextを表示し、メニューで送信が押されたら結果を取得

### 難度

簡単。Hello Worldプラスアルファ程度。

**Comment by harukawa** [comment]
挑戦してみます。

**Comment by karino2** [comment]
### マッシュルームの概要と使い方

AndroidのIME、例えばshimejiやGoogleI日本語入力では、マッシュルームという拡張が使える。
Google日本語入力の場合、

1. 左下の「あa」を長押し
2. 出てきた歯車を選ぶ（ただ離すだけ）
3. マッシュルームを起動、を選ぶ

これでマッシュルームから来た文字列を、入力として入れる事が出来ます。

### マッシュルームの例

以下の二つが割と単純なマッシュルームアプリ

- https://github.com/karino2/ClipboardMush
- https://github.com/karino2/TextBluetoothShareMash

### マッシュルームのプロトコル

特殊なintentに反応するアプリになっている。

まず以下のようなintent-filterを書く。

```
            <intent-filter>
                <action android:name="com.adamrocker.android.simeji.ACTION_INTERCEPT" />
                <category android:name="com.adamrocker.android.simeji.REPLACE" />
            </intent-filter>
```

詳細は[このあたり](https://github.com/karino2/ClipboardMush/blob/master/app/src/main/AndroidManifest.xml)を参照。

次に、ActivityのsetResultで、replace_keyというキーでデータを入れる([参考](https://github.com/karino2/ClipboardMush/blob/master/app/src/main/java/io/github/karino2/clipboardmush/MainActivity.kt))

**Comment by harukawa** [comment]
[https://github.com/harukawa/MultipleLinesInputMush](https://github.com/harukawa/MultipleLinesInputMush)にrepositoryを作成しました。

**Comment by karino2** [comment]
google IMEがなぜかgitterアプリにマッシュルーム入力を入れてくれないので、自分が使えませんでした。
この課題は失敗だったという事でcloseします…
