### ISSUE TITLE
数式表示のデモアプリ（単独アプリ、やや簡単）

### ISSUE THREAD

**Issue by karino2** [karino2/kotlin-lesson#14]
### 概要

kotlitexのデモアプリが欲しい。EditTextとListViewを同じ画面に配置して表示する。
Google Playで配布したい。

### 作業内容

作りたい物の説明とかぶってしまうので、作りたい物の機能を列挙しておきます。

- 画面の上1/4くらいにEditTextを置いて、下3/4にスクロールするListViewを置く。
- ListViewにはkotlitexのMarkdownViewを張る。
- ListViewはArrayAdapterを使って最初にハードコードされた数式などを表示する。
- ListViewで選んだセルの中身をEditTextに表示して編集して反映できる
- 新規セル追加ボタンみたいなのを置いて、ListViewにアイテムを追加出来るようにする（emptyとかいう文字列のセルを追加する）

リストは配列で良いのでDBは要らない。

### 難度

標準的なListViewで表示して編集するアプリと似ているが、SQLiteが要らないのとActivityが一つなので、それよりも簡単。
ただHello Worldとかよりは一段階くらい難しいので、「やや簡単」くらいとします。

自分がやれば3時間くらい。

**Comment by karino2** [comment]
まず最初の段階でやる事。

- プロジェクトの名前はkotlitexdemoとし、kotlitexのsampleと同じような感じの階層に置く
- gitのブランチを切る。名前はdemoで。
- 画面の上1/4にEditText、下3/4にListViewを置く
- ListViewにはとりあえずハードコードした配列のArrayAdapterを表示する。中身はTextView。
- ListViewのアイテムが選ばれたら、中身を上のEditTextに入れる

とりあえずまずはこの辺から始めて下さい。

**Comment by harukawa** [comment]
[https://github.com/harukawa/kotlitexdemo](https://github.com/harukawa/kotlitexdemo)にリポジトリを作成しました。

**Comment by karino2** [comment]
gitterでもいいましたが、やっぱりkotlitexのレポジトリにdemoappという名前で入れて下さい。（記録の為書いておく）

**Comment by harukawa** [comment]
[PR](https://github.com/karino2/kotlitex/pull/136)を作成しました。

**Comment by karino2** [comment]
1. ListViewの中身をMarkdownViewに差し替える
2. setTextだった所をsetMarkdownに変える
3. サンプルのコンテンツをもうちょっと数式とテキストが入り混じった物にする

次はこの辺をやってみてもらえますか？
sampleのアプリが参考になると思うので。

**Comment by karino2** [comment]
完成ということで閉じます。
お疲れさまでした。
