### ISSUE TITLE
ブログ投稿アプリ（github pages）(単独アプリ、やや簡単～普通）

### ISSUE THREAD

**Issue by karino2** [karino2/kotlin-lesson#19]
### 概要

github pagesのブログに投稿するだけのアプリ。
起動するとEditTextが立ち上がって書いて投稿ってやるだけ、みたいな感じにしたい。

### 作業内容

- ヘッダに相当する物を設定する設定画面
- prefに保存
- githubのoauth認証と送信（手抜きだけどコードはあるので提供出来ます）
- coroutine（送信回りだけ。理解出来てなくても作れるとは思う）

### 難度

通信回りはちょっと難しいが既存のコードがあるのでそんな苦労は無いと思う。
他は入門的なアプリの範囲に思う。

「やや簡単」くらいと思うけれど、それなりに書くコードがあるので「やや簡単～普通」くらいにしておきます。

**Comment by karino2** [comment]
あんまいいコードじゃないけど、この辺。

https://github.com/karino2/Mpd2Github/blob/master/app/src/main/java/io/github/karino2/mpd2github/GithubPostBaseActivity.kt

**Comment by karino2** [comment]
アプリとしてはこれが似てる（ただしマッシュルーム周りは要らない）

https://github.com/karino2/TextBluetoothShareMash/blob/master/app/src/main/java/com/livejournal/karino2/textbluetoothsharemash/MainActivity.kt

**Comment by karino2** [comment]
とりあえずは上記を参考にEditTextだけを持ったアプリを作って、送信、というActionBarのメニューを選んだら投稿するアプリを作る。

ここまで出来たら次に、以前書いたのを編集する機能をつけたい。こちらはこのアプリから投稿された物だけを覚えておいてできる、くらいで良い。
最悪最後に投稿したのだけ更新出来れば良いかな。

**Comment by karino2** [comment]
名前とかは好きにしてください。このアプリは自分は単にユーザーとして使いたいだけなので。

**Comment by harukawa** [comment]
作成します。

**Comment by harukawa** [comment]
テキストの送信と前回の編集を行えるところまで作成出来たので、[リポジトリ](https://github.com/harukawa/PostGithubPages)を作成しました。

**Comment by karino2** [comment]
Done
