### ISSUE TITLE
ZipSourceCodeReadingのRuntime permission対応（機能追加、簡単）

### ISSUE THREAD

**Issue by karino2** [karino2/kotlin-lesson#3]
### 概要

ソースコード読みアプリ、ZipSourceCodeReadingにRuntime permissionの対応を入れる。
https://github.com/karino2/ZipSourceCodeReading/issues/11

external storageのwritableくらいだった気がする。

### 難易度

凄い簡単。たぶん6行くらいで出来る。PRの練習とかにオススメ。

**Comment by karino2** [comment]
1. 使ってるpermissionをAndroidManifests.xmlを見て確認
2. 設定から権限をオフにしてみて起動して落ちるのを確認
3. 以下を参考にパミッションをリクエストするコードを追加し、落ちなくなっている事を確認

- https://github.com/karino2/WhiteBoardCast/commit/1e0dea83f7469de6108b91f1afc9f15c88b5b9fe
- https://github.com/karino2/ItsuNani/commit/fe422c391ab4a5f3f138538e30a880d684cb1950

**Comment by Oikawa124** [comment]
この課題に取り組みます。

**Comment by karino2** [comment]
https://github.com/karino2/ZipSourceCodeReading/pull/13
https://github.com/karino2/ZipSourceCodeReading/pull/14

で終わり。
